name: Web Tests (Cross-browser Parallel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build all modules
        run: mvn clean install -DskipTests

      - name: Run Web Tests (Chrome + Firefox)
        run: |
          cd qa-web-automation
          mvn test -Dsuite=testng-web.xml

      - name: Upload Allure Results Artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: qa-web-automation/target/allure-results

      - name: Publish Allure Report to GitHub Pages
        uses: erikzaadi/allure-report@v2
        if: always()
        with:
            WORKING_DIR: qa-web-automation/target/allure-results
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            REPORT_PATH: /
